image: docker:latest
variables:
  APP_NAME: ${APP_NAME}
  DOCKER_REGISTRY: ${DOCKER_REGISTRY}
  IMAGE_NAME: "${DOCKER_REGISTRY}:latest"

stages:
  - docker-image
  - ecs-update

docker image:
  stage: docker-image
  before_script:
    - docker info
  services:
    - docker:dind
  script:
    - apk add --no-cache zip
    - apk add --no-cache curl jq python3 py3-pip
    - pip3 install awscli
    - docker build -t ${IMAGE_NAME} .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker tag ${IMAGE_NAME} ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}

ecs update:
  stage: ecs-update
  script:
    - apk add --no-cache zip
    - apk add --no-cache curl jq python3 py3-pip
    - pip3 install awscli
    - aws ecs update-service --cluster JmeterResultsECS --service JMETER-RESULT --force-new-deployment
